"""Phase 2 enhancements

Revision ID: 0c608ee58755
Revises: 067ff553ad01
Create Date: 2026-03-24 00:18:28.497924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c608ee58755'
down_revision: Union[str, Sequence[str], None] = '067ff553ad01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=3),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('subtotal',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('invoice_returns', schema=None) as batch_op:
        batch_op.alter_column('total_refunded',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('refund_method',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offline_uuid', sa.String(length=50), nullable=True))
        batch_op.alter_column('total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('discount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('tax_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('final_total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('is_paid',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['offline_uuid'])

    with op.batch_alter_table('product_barcodes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('buy_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_activity_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('invoices_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_sales', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('total_sales')
        batch_op.drop_column('invoices_count')
        batch_op.drop_column('last_activity_at')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('buy_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('product_barcodes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('is_paid',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=True)
        batch_op.alter_column('final_total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('tax_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'"),
               existing_nullable=True)
        batch_op.alter_column('tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text("'0'"),
               existing_nullable=True)
        batch_op.alter_column('discount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('offline_uuid')

    with op.batch_alter_table('invoice_returns', schema=None) as batch_op:
        batch_op.alter_column('refund_method',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'cash'"),
               existing_nullable=True)
        batch_op.alter_column('total_refunded',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'"),
               existing_nullable=True)

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.alter_column('subtotal',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
